### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Zarkness2** [aMelonRind/JsMacros-scripts#2]
I was wondering how I could make a script which detects that when they have x amount of y item that runs the command /pv 4 and move those items to that menu and then close it and it is running in a loop until I stop it, and I was wondering if you could help me by giving me an example of how it could be done.

**Comment by aMelonRind** [comment]
ask in [jsmacros discord](https://discord.gg/P6W58J8)

**Comment by Zarkness2** [comment]
thx
